### ISSUE TITLE
Make hardcoded annotation classes configurable

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/event-impl-gen#7]
Because event impl gen has more uses than just the SpongeAPI events, I'd hope that we'd be able to make it configurable through gradle to use a particular set of annotations through the gradle build configuration files or something thereof (just like how the SpongeEventFactory is set). Ideally, this would allow for more than just SpongeAPI projects to be able to use the plugin. If the annotations are meant for specific needs, can make them hard values that are needed to use the plugin.

**Comment by liach** [comment]
In #5, I allowed each event impl generation task to specify its own set of inclusive/exclusive annotations. Is that desirable?
