### ISSUE TITLE
Java 11 compatibility

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/event-impl-gen#8]
`./gradlew build --refreresh-dependencies` for SpongeCommpon API-8 (https://github.com/SpongePowered/SpongeCommon/commit/bf58635b1829d951718377f0716d830d5c838ff1) throws this error:
```
* What went wrong:
Execution failed for task ':SpongeAPI:genEventImpl'.
> Unrecognized option : -1.11
```

**Comment by zml2008** [comment]
Fixed in 2e22516ae349a417bfef5bd79b258952404394de
